// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoRecorderUDP.proto

#ifndef PROTOBUF_VideoRecorderUDP_2eproto__INCLUDED
#define PROTOBUF_VideoRecorderUDP_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace VideoRecorderRemote {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_VideoRecorderUDP_2eproto();
void protobuf_AssignDesc_VideoRecorderUDP_2eproto();
void protobuf_ShutdownFile_VideoRecorderUDP_2eproto();

class VideoRecorderUDP;

// ===================================================================

class VideoRecorderUDP : public ::google::protobuf::Message {
 public:
  VideoRecorderUDP();
  virtual ~VideoRecorderUDP();

  VideoRecorderUDP(const VideoRecorderUDP& from);

  inline VideoRecorderUDP& operator=(const VideoRecorderUDP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VideoRecorderUDP& default_instance();

  void Swap(VideoRecorderUDP* other);

  // implements Message ----------------------------------------------

  VideoRecorderUDP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VideoRecorderUDP& from);
  void MergeFrom(const VideoRecorderUDP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string FileName = 1;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFileNameFieldNumber = 1;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  inline void set_allocated_filename(::std::string* filename);

  // required bool IsEnd = 2;
  inline bool has_isend() const;
  inline void clear_isend();
  static const int kIsEndFieldNumber = 2;
  inline bool isend() const;
  inline void set_isend(bool value);

  // @@protoc_insertion_point(class_scope:VideoRecorderRemote.VideoRecorderUDP)
 private:
  inline void set_has_filename();
  inline void clear_has_filename();
  inline void set_has_isend();
  inline void clear_has_isend();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* filename_;
  bool isend_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_VideoRecorderUDP_2eproto();
  friend void protobuf_AssignDesc_VideoRecorderUDP_2eproto();
  friend void protobuf_ShutdownFile_VideoRecorderUDP_2eproto();

  void InitAsDefaultInstance();
  static VideoRecorderUDP* default_instance_;
};
// ===================================================================


// ===================================================================

// VideoRecorderUDP

// required string FileName = 1;
inline bool VideoRecorderUDP::has_filename() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VideoRecorderUDP::set_has_filename() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VideoRecorderUDP::clear_has_filename() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VideoRecorderUDP::clear_filename() {
  if (filename_ != &::google::protobuf::internal::kEmptyString) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& VideoRecorderUDP::filename() const {
  return *filename_;
}
inline void VideoRecorderUDP::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void VideoRecorderUDP::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void VideoRecorderUDP::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* VideoRecorderUDP::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  return filename_;
}
inline ::std::string* VideoRecorderUDP::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void VideoRecorderUDP::set_allocated_filename(::std::string* filename) {
  if (filename_ != &::google::protobuf::internal::kEmptyString) {
    delete filename_;
  }
  if (filename) {
    set_has_filename();
    filename_ = filename;
  } else {
    clear_has_filename();
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bool IsEnd = 2;
inline bool VideoRecorderUDP::has_isend() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VideoRecorderUDP::set_has_isend() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VideoRecorderUDP::clear_has_isend() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VideoRecorderUDP::clear_isend() {
  isend_ = false;
  clear_has_isend();
}
inline bool VideoRecorderUDP::isend() const {
  return isend_;
}
inline void VideoRecorderUDP::set_isend(bool value) {
  set_has_isend();
  isend_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace VideoRecorderRemote

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_VideoRecorderUDP_2eproto__INCLUDED
